#pragma once

#include "App.g.h" // generated by gen-projection.sh from app.idl
#include "pch.h"

#include <memory>

namespace hello {
class MainPage;
}

namespace winrt::hello::implementation {

struct App : AppT<App> {
    App();
    void OnLaunched(winrt::Windows::ApplicationModel::Activation::LaunchActivatedEventArgs const&);

  private:
    std::shared_ptr<::hello::MainPage> m_page;
};

} // namespace winrt::hello::implementation

namespace winrt::hello::factory_implementation {

struct App : AppT<App, implementation::App> {};

} // namespace winrt::hello::factory_implementation
